# Large displacement elastic lubrication in 2D with scanning over displacement
#

run:
	$(ELMER_GRID) 1 2 bump
	$(ELMER_SOLVER)

clean:
	/bin/rm test.log temp.log mon.out f.dat f.dat.names
	/bin/rm -r bump
