include(test_macros)
execute_process(COMMAND ${ELMERGRID_BIN} 1 2 radiator)
execute_process(COMMAND ${RADIATORS_BIN})
execute_process(COMMAND ${ELMERGRID_BIN} 2 2 radiator -metis ${MPIEXEC_NTASKS} 3 -partdual)
RUN_ELMER_TEST()
