== Elmer FEM

This is the official source code repository for the Elmer FEM software suite.

=== Abstract:

[.text-justify]
Elmer is a finite element software for numerical solution of partial differential equations. Elmer is capable of handling any number of equations and is therefore ideally suited for the simulation of multiphysical problems. It includes models, for example, of structural mechanics, fluid dynamics, heat transfer and electromagnetics. Users can also write their own equations that can be dynamically linked with the main program.

Elmer consists of several parts. The most important ones are ElmerSolver, the finite element solver, ElmerGUI, the graphical user interface, and ElmerGrid, the mesh creation and manipulation tool. Also a visualization tool, ElmerPost, is included in the package but it is no longer developed.  


=== Compiling:

==== Linux
 * See instructions in https://github.com/ElmerCSC/elmerfem/wiki/Compilation

==== macOS:

 * Install HomeBrew
 * Install GNU GCC `brew install gcc`
 * Install CMake `brew install cmake`
 * Install OpenMPI `brew install open-mpi`
 * go to the build directory `cd build`
 * `cmake ..`
 * `make`

=== Licencing:

[.text-justify]
Elmer software is licensed under GPL except for the ElmerSolver library which is licensed under LGPL license. Elmer is mainly developed at CSC - IT Center for Science, Finland. However, there have been numerous contributions from other organizations and developers
as well, and the project is open for new contributions.

