include(test_macros)
execute_process(COMMAND ${ELMERGRID_BIN} 1 2 two_plates.grd)
execute_process(COMMAND ${VIEWFACTORS_BIN})
execute_process(COMMAND ${ELMERGRID_BIN} 2 2 two_plates -metis ${MPIEXEC_NTASKS} 3 -partdual)
RUN_ELMER_TEST()
