#!/bin/sh

export CC="cccl2 -link:static"
export CXX="cccl2 -link:static"
export FC="cccl2 -link:static"
export F77="cccl2 -link:static"
# export CFLAGS="-O"
# export CXXFLAGS="-O" 
export FFLAGS="-O -link:static"
export FCFLAGS="-O -link:static"
export BLAS_LIBS="/home/admin/win32/lib/libblas.a"
export LAPACK_LIBS="/home/admin/win32/lib/liblapack.a"
export HUTI_LIBS="/home/admin/win32/lib/libhuti.a"
export EIOF_LIBS="/home/admin/win32/lib/libeiof.a"
export ARPACK_LIBS="/home/admin/win32/lib/libarpack.a"
export UMFPACK_LIBS="/home/admin/win32/lib/libumfpack.a /home/admin/win32/lib/libamd.a"
export MATC_LIBS="/home/admin/win32/lib/libmatc.a"
export TCLTK_LIBS="/home/admin/src/ELMER4.0/lib/tk83.lib /home/admin/src/ELMER4.0/lib/tcl83.lib"
export TCLTK_INCPATH="/home/admin/src/ELMER4.0/include"