# Qt4 dynamic link libraries for ElmerGUI
FIND_FILE(QTCORE_DLL QtCore4.dll PATH_SUFFIXES "bin")
FIND_FILE(QTGUI_DLL QtGui4.dll PATH_SUFFIXES "bin")
FIND_FILE(QTOPENGL_DLL QtOpenGL4.dll PATH_SUFFIXES "bin")
FIND_FILE(QTSCRIPT_DLL QtScript4.dll PATH_SUFFIXES "bin")
FIND_FILE(QTXML_DLL QtXml4.dll PATH_SUFFIXES "bin")
FIND_FILE(QTSVG_DLL QtSvg4.dll PATH_SUFFIXES "bin")

INSTALL(FILES ${QTCORE_DLL} ${QTGUI_DLL} ${QTOPENGL_DLL} ${QTSCRIPT_DLL} ${QTXML_DLL} ${QTSVG_DLL} DESTINATION "bin" COMPONENT "elmerclips")

# mingw runtime dynamic link libraries
FIND_FILE(MINGW_GFORT_LIB libgfortran-3.dll)
FIND_FILE(QUADMATH_LIB libquadmath-0.dll)
FIND_FILE(WINPTHREAD_LIB libwinpthread-1.dll)
FIND_FILE(GCC_LIB libgcc_s_sjlj-1.dll)
FIND_FILE(STDCPP_LIB libstdc++-6.dll)

INSTALL(FILES ${MINGW_GFORT_LIB} ${QUADMATH_LIB} ${WINPTHREAD_LIB} ${GCC_LIB} ${STDCPP_LIB} ${BLAS_LIB} ${LAPACK_LIB} DESTINATION "bin")

