include(test_macros)
execute_process(COMMAND ${ELMERGRID_BIN} 1 2 radiation)
execute_process(COMMAND ${VIEWFACTORS_BIN})
execute_process(COMMAND ${ELMERGRID_BIN} 2 2 radiation -metis ${MPIEXEC_NTASKS} 3 -partdual)
RUN_ELMER_TEST()
