#cmakedefine ELMER_FEM_VERSION "${ELMER_FEM_VERSION}" 
#cmakedefine ELMER_FEM_REVISION "${ELMER_FEM_REVISION}" 
#cmakedefine ELMER_FEM_BRANCH "${ELMER_FEM_BRANCH}" 
#cmakedefine ELMER_FEM_COMPILATIONDATE "${ELMER_FEM_COMPILATIONDATE}" 
