# Hierarchical coupling of Structural eigenmodes and Helmholtz equation 
#

run:
	$(ELMER_GRID) 1 2 block.grd
	$(ELMER_SOLVER)

clean:
	/bin/rm mon.out
	/bin/rm -rf temp.log test.log 
	/bin/rm -r block
