# cmake script for finding MUMPS sparse direct solver
cmake_minimum_required(VERSION 2.8)

message(STATUS "Finding SCALAPACK")

# Find SCALAPACK root directory
IF (SCALAPACKROOT)
   SET(SCALAPACKLIB ${SCALAPACKROOT})
ELSEIF (DEFINED ENV{SCALAPACKROOT})
   SET(SCALAPACKLIB $ENV{SCALAPACKROOT})
ELSE()
   SET(SCALAPACKLIB ${CMAKE_SOURCE_DIR}/scalapack)
ENDIF()
 
# MESSAGE(STATUS "SCALAPACKLIB set to ${SCALAPACKLIB}")

# Try to find SCALAPACK
FIND_LIBRARY(SCALAPACK_LIBRARIES scalapack ${SCALAPACKLIB})

IF (SCALAPACK_LIBRARIES)
   SET(SCALAPACK_FOUND TRUE)
ENDIF()
   
IF (SCALAPACK_FOUND)
   IF (NOT SCALAPACK_FIND_QUIETLY)
      MESSAGE(STATUS "A library with SCALAPACK API found.")
      MESSAGE(STATUS "SCALAPACK libraries: ${SCALAPACK_LIBRARIES}")
   ENDIF()
ELSE()
   IF (SCALAPACK_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "SCALAPACK library not found.")
   ENDIF()
ENDIF()

MARK_AS_ADVANCED(SCALAPACK_LIBRARIES)