# cmake script for finding MUMPS sparse direct solver
cmake_minimum_required(VERSION 2.8)

message(STATUS "Finding SCALAPACK")

# Find SCALAPACK root directory
IF (SCALAPACKROOT)
  # SCALAPACKROOT CMake variable
  SET(SCALAPACKLIB ${SCALAPACKROOT})
ELSEIF (DEFINED ENV{SCALAPACKROOT})
  # SCALAPACKROOT environment variable
  SET(SCALAPACKLIB $ENV{SCALAPACKROOT})
ELSE()
  # fem/../scalapack
  SET(SCALAPACKLIB ${CMAKE_SOURCE_DIR}/scalapack)
ENDIF()
 
# Try to find SCALAPACK
# TODO: add names of other scalapack libraries here
SET(SCALAPACKNAME "scalapack-openmpi" CACHE STRING "Names of scalapack library to look for")
FIND_LIBRARY(SCALAPACK_LIBRARIES
  NAMES
  ${SCALAPACKNAME}
  HINTS
  ${SCALAPACKLIB})

IF (SCALAPACK_LIBRARIES)
  SET(SCALAPACK_FOUND TRUE)
ENDIF()
   
IF (SCALAPACK_FOUND)
  IF (NOT SCALAPACK_FIND_QUIETLY)
    MESSAGE(STATUS "A library with SCALAPACK API found.")
    MESSAGE(STATUS "SCALAPACK libraries: ${SCALAPACK_LIBRARIES}")
  ENDIF()
ELSE()
  IF (SCALAPACK_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "SCALAPACK library not found.")
  ENDIF()
ENDIF()

MARK_AS_ADVANCED(
  SCALAPACK_LIBRARIES 
  SCALAPACKNAME
  )
