INCLUDE(${TEST_SOURCE}/../test_macros.cmake)

FILE(COPY ${PROJECT_SOURCE_DIR}/..//Solvers/MeshAdaptation_2D/Script_Transient.sh  DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/")

FILE(COPY ${PROJECT_SOURCE_DIR}/MMG2D_Transient/MESH_I0_J0  DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/")

EXECUTE_PROCESS(COMMAND bash ./Script_Transient.sh)

RUN_ELMERICE_TEST()
