INCLUDE(${TEST_SOURCE}/../test_macros.cmake)

FILE(COPY ${PROJECT_SOURCE_DIR}/..//Solvers/MeshAdaptation_2D/Script_Transient.sh  DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/")

FILE(COPY ${PROJECT_SOURCE_DIR}/MMG2D_Transient/MESH_I0_J0  DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/")


# RUN TEST
FILE(REMOVE "TEST.PASSED")

SET(ENV{ELMERSOLVER_BIN} "${ELMERSOLVER_BIN}")
EXECUTE_PROCESS(COMMAND sh -c ". ./Script_Transient.sh" 
	        OUTPUT_FILE "test-stdout.log"
		ERROR_FILE "test-stderr.log")

FILE(READ "TEST.PASSED" RES)
IF(NOT RES EQUAL "1")
  MESSAGE(FATAL_ERROR "Test failed")
ENDIF()
