OBJ_EXT	=	.o

include make.inc

LIBDIR	=	$(ELMER_PREFIX)/lib
LIB	=	libviewaxis.a

CC	=	cxx
CP	=	cp

.SUFFIXES:	.cxx

.cxx.o:
	$(CC) -c -I. -0 $<
	ar r $(LIB) $@

$(LIB):	$(OBJS)
	$(CP) $(LIB) $(LIBDIR)
