OBJ_EXT	=	.o

include make.inc

LIBDIR	=	$(ELMER_PREFIX)/lib
LIB	=	libviewaxis.a

CC	=	g++ -DLINUX_PC
CP	=	cp
RM	=	rm -f

.SUFFIXES:	.cxx

.cxx.o:
	$(CC) -c -I. -O $<
	ar r $(LIB) $@

$(LIB):	$(OBJS) install

install:

clean:
	$(RM) *.o $(LIB)
