/*
 * elmerld - wrapper to link Elmer solver plugins as shared libraries.
 * Generated by CMake from elmerld.in.c; do not edit this file.
 *
 * Logic:
 *   1. Determine LIBDIR from env (ELMER_LIB, ELMER_HOME) or baked-in paths.
 *   2. Determine the Fortran compiler from ELMER_Fortran_COMPILER or the build-time default.
 *   3. Optionally append ElmerIce / MMG / ParMMG flags.
 *   4. exec the linker (the compiler is used as the linker driver) with the assembled argument list.
 */

#ifdef _WIN32
#  include <process.h>   /* _execvp */
#  define execvp _execvp
#else
#  include <unistd.h>    /* execvp */
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* --- CMake-configured constants ------------------------------------------ */

#define ELMERF90_LD            "@CMAKE_Fortran_COMPILER@"
#define ELMERF90_LIBDIR        "@ELMER_SOLVER_HOME@/../../@ELMER_INSTALL_LIB_DIR@"
#define ELMERF90_INSTALL_LIB   "@ELMER_INSTALL_LIB_DIR@"

/* Compile flags are baked in as a single whitespace-separated string and
   split at runtime, matching shell word-splitting behaviour. */
#define ELMERF90_FFLAGS \
    "@CMAKE_Fortran_FLAGS@ " \
    "@CMAKE_SHARED_LIBRARY_Fortran_FLAGS@ " \
    "@CMAKE_SHARED_LIBRARY_CREATE_Fortran_FLAGS@"

#define ELMERF90_HAVE_ELMERICE  @HAVE_ELMERICE_INT@
#define ELMERF90_HAVE_MMG       @HAVE_MMG_INT@
#define ELMERF90_MMG_LIBDIR     "@MMG_LIBDIR@"
#define ELMERF90_HAVE_PARMMG    @HAVE_PARMMG_INT@
#define ELMERF90_PARMMG_LIBDIR  "@PARMMG_LIBDIR@"

/* --- Argument-list helpers ----------------------------------------------- */

#define MAX_ARGS 1024

static char *args[MAX_ARGS];
static int  nargs = 0;

static void push(const char *s)
{
    if (nargs >= MAX_ARGS - 1) {
        fprintf(stderr, "elmerf90: too many arguments\n");
        exit(1);
    }
    args[nargs++] = strdup(s);
}

/* Split a whitespace-separated flag string and push each token. */
static void push_flags(const char *flags)
{
    if (!flags || !*flags) return;
    char *copy = strdup(flags);
    // FIXME: Handle double quoted paths that might contain whitespace.
    char *tok  = strtok(copy, " \t\n");
    while (tok) {
        push(tok);
        tok = strtok(NULL, " \t\n");
    }
    free(copy);
}

static char *join(const char *a, const char *b)
{
    size_t la = strlen(a), lb = strlen(b);
    char *r = malloc(la + lb + 1);
    memcpy(r, a, la);
    memcpy(r + la, b, lb + 1);
    return r;
}

/* --- main --------------------------------------------------------------- */

int main(int argc, char *argv[])
{
    const char *env_lib  = getenv("ELMER_LIB");
    const char *env_home = getenv("ELMER_HOME");
    const char *env_fc   = getenv("ELMER_Fortran_COMPILER");

    /* Resolve LIBDIR and INCLUDE (mirrors shell-script priority) */
    char *libdir;
    if (env_lib && *env_lib) {
        libdir = strdup(env_lib);
    } else if (env_home && *env_home) {
        libdir = join(env_home, "/" ELMERF90_INSTALL_LIB);
    } else {
        libdir = strdup(ELMERF90_LIBDIR);
    }

    const char *fc = (env_fc && *env_fc) ? env_fc : ELMERF90_LD;

    /* --- Build argv ---------------------------------------------------- */

    push(fc);

    /* Pass caller's arguments through unchanged */
    for (int i = 1; i < argc; i++)
        push(argv[i]);

    /* Baked-in compiler flags */
    push_flags(ELMERF90_FFLAGS);

    push(join("-L", libdir));

#if ELMERF90_HAVE_ELMERICE
    {
        char *elib = join(libdir, "/../../share/elmersolver/lib");
        fprintf(stderr, "with elmerice\n");
#ifndef _WIN32
        /* rpath is a Linux/Mac concept; Windows finds DLLs via PATH */
        push("-Xlinker");
        push(join("-rpath=", elib));
#endif
        push(join("-L", elib));
        free(elib);
        push("-lElmerIceSolvers");
        push("-lElmerIceUSF");
        push("-lElmerIceUtils");
    }
#else
    fprintf(stderr, "no elmerice\n");
#endif

#if ELMERF90_HAVE_MMG
    fprintf(stderr, "with MMG\n");
    if (*ELMERF90_MMG_LIBDIR) push(join("-L", ELMERF90_MMG_LIBDIR));
#endif

#if ELMERF90_HAVE_PARMMG
    fprintf(stderr, "with ParMMG\n");
    {
        int same_lib = strcmp(ELMERF90_PARMMG_LIBDIR, ELMERF90_MMG_LIBDIR) == 0;
        if (!same_lib) {
            if (*ELMERF90_PARMMG_LIBDIR) push(join("-L", ELMERF90_PARMMG_LIBDIR));
        } else {
            fprintf(stderr, "MMG and ParMMG share the same lib dir\n");
        }
    }
#endif

    push("-lelmersolver");
    args[nargs] = NULL;

    /* Print the command (matches shell script behaviour) */
    for (int i = 0; i < nargs; i++)
        printf("\"%s\" ", args[i]);
    printf("\n");

    execvp(fc, args);
    perror("elmerld: exec");
    return 127;
}
