/*
 * helper functions for the elmerf90 and elmerld wrappers
 * Generated by CMake from elmerf90-helper.in.h; do not edit this file.
 */

#ifdef _WIN32
#  include <process.h>   /* _execvp */
#  define execvp _execvp
#else
#  include <unistd.h>    /* execvp */
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* --- CMake-configured constants ------------------------------------------ */

#define ELMERF90_FC            "@CMAKE_Fortran_COMPILER@"
#define ELMERF90_LIBDIR        "@ELMER_SOLVER_HOME@/../../@ELMER_INSTALL_LIB_DIR@"
#define ELMERF90_INCLUDE_DIR   "@ELMER_SOLVER_HOME@/include"
#define ELMERF90_INSTALL_LIB   "@ELMER_INSTALL_LIB_DIR@"

/* Compile flags are baked in as a single whitespace-separated string and
   split at runtime, matching shell word-splitting behaviour. */
/* FIXME: Paths with spaces in these flags are not handled correctly. */
#define ELMERF90_FFLAGS \
    "@CMAKE_Fortran_FLAGS@ @ELMER_F90FLAGS@ " \
    "@CMAKE_SHARED_LIBRARY_Fortran_FLAGS@ " \
    "@CMAKE_SHARED_LIBRARY_CREATE_Fortran_FLAGS@"

#define ELMERF90_HAVE_ELMERICE  @HAVE_ELMERICE_INT@
#define ELMERF90_ELMERICESOLVERS_LIB "@ELMERF90_ELMERICESOLVERS_LIB@"
#define ELMERF90_ELMERICEUSF_LIB "@ELMERF90_ELMERICEUSF_LIB@"
#define ELMERF90_ELMERICEUTILS_LIB "@ELMERF90_ELMERICEUTILS_LIB@"
#define ELMERF90_HAVE_MMG       @HAVE_MMG_INT@
#define ELMERF90_MMG_LIBDIR     "@MMG_LIBDIR@"
#define ELMERF90_MMG_INCDIR     "@MMG_INCLUDE_DIR@"
#define ELMERF90_HAVE_PARMMG    @HAVE_PARMMG_INT@
#define ELMERF90_PARMMG_LIBDIR  "@PARMMG_LIBDIR@"
#define ELMERF90_PARMMG_INCDIR  "@PARMMG_INCLUDE_DIR@"

/* --- Argument-list helpers ----------------------------------------------- */

#define MAX_ARGS 1024

static char *args[MAX_ARGS];
static int  nargs = 0;

static void push(const char *s)
{
    if (nargs >= MAX_ARGS - 1) {
        fprintf(stderr, "elmerf90: too many arguments\n");
        exit(1);
    }
    args[nargs++] = strdup(s);
}

/* Split a whitespace-separated flag string and push each token. */
static void push_flags(const char *flags)
{
    if (!flags || !*flags) return;
    char *copy = strdup(flags);
    /* FIXME: Handle double quoted paths that might contain whitespace. */
    char *tok  = strtok(copy, " \t\n");
    while (tok) {
        push(tok);
        tok = strtok(NULL, " \t\n");
    }
    free(copy);
}

static char *join(const char *a, const char *b)
{
    size_t la = strlen(a), lb = strlen(b);
    char *r = malloc(la + lb + 1);
    memcpy(r, a, la);
    memcpy(r + la, b, lb + 1);
    return r;
}
