name: "nix build and push to cache"
on:
  workflow_dispatch:
  push:
    branches:
      - devel

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - uses: cachix/cachix-action@v14
      with:
        name: elmerfem
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: nix build
      run: |
        nix build -L
        nix build .#gui -L
        nix build .#full -L
