# initially infinitely elastic bodies activated during the simulation
# with stresses computed relative to the activation shape 
#
run:
	$(ELMER_GRID) 1 2 mesh.grd
	$(ELMER_SOLVER)


clean:
	/bin/rm test.log temp.log
	/bin/rm -r mesh
